name: Build and publish graffiti

on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  backend:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - { name: jeb, type: pack }
          - { name: intellij, type: java }
          - { name: clion, type: java }
          - { name: ida, type: pack }
          - { name: vscode, type: typescript }
          - { name: opengrok_sourcegraph, type: typescript }
          - { name: jadx, type: pack }
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        if: matrix.target.type == 'typescript'

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "19"
        if: matrix.target.type == 'java'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 7.6
        if: matrix.target.type == 'java'

      - name: Configure
        run: make init

      - name: Build ${{ matrix.target.name }}
        run: make ${{ matrix.target.name }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v4.3.2
        with:
          name: Graffiti for ${{ matrix.target.name }}
          path: out/*
  frontend:
    runs-on: ubuntu-latest
    needs: backend
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure
        run: make init

      - name: Build web frontend
        run: make web

      - name: Upload Artifact
        uses: actions/upload-artifact@v4.3.2
        with:
          name: Graffiti web frontend
          path: out/*

      - name: Download backends
        uses: actions/download-artifact@v4
        with:
          path: /tmp/artifacts

      - name: Copy backends
        run: find /tmp/artifacts -type f -exec cp -v {} out/ \;

      - name: Pack web frontend with backends
        run: make web-collect

      - name: Upload Artifact
        uses: actions/upload-artifact@v4.3.2
        with:
          name: Graffiti Web frontend with backends
          path: out/*_frontend_web_with_deps.zip

  publish:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' && github.event_name == 'push'
    needs: frontend
    steps:
      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Download web frontend
        uses: actions/download-artifact@v4
        with:
          path: /tmp
          name: Graffiti Web frontend with backends

      - name: Unzip web frotnend
        run: mkdir /tmp/web && unzip /tmp/*_frontend_web_with_deps.zip -d /tmp/web

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: /tmp/web

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
