name: Build and publish graffiti

on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Setup NodeJS
        uses: actions/setup-node@v4
      - name: Setup JDK
        uses: actions/setup-java@v4
      - name: Checkout code
        uses: actions/checkout@v4
  build:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Build server
        run: make server

      - name: Build frontends
        run: make frontends

      - name: Build backends
        run: make backends

      - name: Collect Web frontend
        run: make web-collect

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4.3.2
        with:
          name: Graffiti artifacts
          path: out/*
